services:
  - type: web
    name: real-estate-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: ATLAS_URI
        sync: false
      - key: PORT
        value: 5000
