services:
  - type: web
    name: real-estate-backend
    env: node
    region: singapore
    plan: free
    rootDir: Backend
    buildCommand: npm ci || npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: ATLAS_URI
        sync: false
      - key: PORT
        value: 5000
